export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_MENU_SUCCESS = 'FETCHING_DATA_MENU_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
export const STORE_ADD = 'STORE_ADD';
export const BADGE_ADD = 'BADGE_ADD';
export const STORE_REMOVE = 'STORE_REMOVE';
export const BADGE_REMOVE = 'BADGE_REMOVE';
